### ISSUE TITLE
Can't reproduce the results on my machine

### ISSUE THREAD

**Issue by emanuelelunardi** [FloydZ/decoding#4]
Good afternoon, i'm trying to reproduce the results of your paper with my machine but there are some problems in the building phase: some errors are generated and i think the cause is the failing cloning of the submodule cryptanalysislib.
Initially, cloning the directory with the command reported in the reproduction of results section (git clone --recurse-submodules -j4 https://github.com/FloydZ/decoding), causes a fail in cloning the submodule cryptanalysislib. Even trying to manually cloning it in the right place and at the right commit doesn't resolve the errors coming out building the project. All the errors signaled after calling the python command or after calling make in cmake-build-release are inside files having as the parent directory cryptoanalysislib.

Thank you in advance, have a good evening
Goodbye

**Comment by FloydZ** [comment]
Hi,
did you run the `./setup.sh` script? Make sure that this script runs whithout errors. Specially make sure that M4RI is correctly checkout at branch `042cab8`. If its still not compiling just post the error msg here , so i can understand the problem better.

Cheers

**Comment by emanuelelunardi** [comment]
Good afternoon and thanks for answering me
First, when i try to clone the decoding repository with git clone --recurse-submodules -j4 https://github.com/FloydZ/decoding a fatal error occurs: 
fatal: No url found for submodule path 'deps/cryptanalysislib/deps/g6k' in .gitmodules
and this causes "Failed to recurse into submodule path 'deps/cryptanalysislib'".
For this reason i need to manually cloning this submodule at the right place and at the commit reported in the github page.

After creating the build directory following the instructions i run ./setup.sh and it runs for a minute/few minutes: there is an error that i didn't see before because after it the scripts go on with the work:
error: patch failed: m4ri/mzd.h:732
error: m4ri/mzd.h: patch does not apply
as i said the script doesn't stop after this and go on checking all the stuff and ends with no other errors but with the message:
mkdir: cannot create directory ‘cmake-build-release’: File exists

Thank you very much, goodbye

**Comment by FloydZ** [comment]
Ah OK I see. g6k is an old submodule which should be deleted at this point: 
```
cd deps/cryptanalysislib/deps
rm g6k
git submodule deinit g6k
```
Should do it. And delete the m4ri subfolder too and rerun the setup script

**Comment by emanuelelunardi** [comment]
I have done it and the script now runs without the previous errors and ends like before with 'mkdir: cannot create directory ‘cmake-build-release’: File exists'.

In the building phase the problems that i said on the first message remains: for example if i run the python command reported on the page i obtain many warnings and the following errors:
error: exception handling disabled, use ‘-fexceptions’ to enable
that can be resolved removing the -fno-exceptions in the CMakeLists.txt and

decoding/src/dumer.h:610:50: error: ‘l1’ was not declared in this scope; did you mean ‘L1’?
  610 |                 size_t S1 = (lsize2 * lsize2) >> l1;
|                                                                           ^~
|                                                                           L1

that will cause an ERROR BUILD.

**Comment by FloydZ** [comment]
ok, is just pushed a fix. Sorry but the repo here on github was a bit outdated, but now everything should work.

**Comment by emanuelelunardi** [comment]
Perfect, now it works, thank you very much, goodbye
