### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by majedhassan1** [FloydZ/decoding#6]
I have followed your instruction. When i entered "git clone --recurse-submodules -j4 git@git.noc.ruhr-uni bochum.de:cits/decoding.git"

i got the message "git@git.noc.ruhr-uni-bochum.de's password:"

what is a password / or how i can get that?

Thanks

**Comment by FloydZ** [comment]
Hey,
Sorry these are the instructions of my internal fork of the project. I updated the readme for this repository on github.

**Comment by majedhassan1** [comment]
Thanks. The problem have solved. But, when i have run "llvm-profdata merge -output=default.profdata default_*.profraw". i have faced with the below error

error: default_*.profraw: No such file or directory

**Comment by FloydZ** [comment]
Just 'touch'  the file. Or ignore the error
